export const BANDWIDTH_PERIOD = 86400;
export const MAX_BLOCK_SIZE = 22020096;
export const RESERVE_RATIO = 1;
export const MAX_CELLULOSE = Number.MAX_SAFE_INTEGER;
export const NETWORK_BANDWIDTH = RESERVE_RATIO * MAX_BLOCK_SIZE * BANDWIDTH_PERIOD;